import pyautogui
from dotenv import load_dotenv
import time

load_dotenv()

def recuperar_shield():

    time.sleep(2)

    x = pyautogui.locateOnScreen('x.png', confidence=0.7)
    pyautogui.moveTo(x)
    time.sleep(2)
    pyautogui.click(x)
    time.sleep(2)

    shield = pyautogui.locateOnScreen('shield.png', confidence=0.7)
    if shield != None:
        pyautogui.moveTo(shield)
        pyautogui.click(shield)
        time.sleep(2)

    more = pyautogui.locateOnScreen('more.png', confidence=0.75)
    if more != None :
        pyautogui.moveTo(more)
        pyautogui.click(more)
        time.sleep(2)

    pyautogui.moveTo(x=456, y=372)
    time.sleep(2)



    info_escudo = (1270, 597, 68, 50)
    escudo_critico = pyautogui.locateOnScreen('pixel_vermelho.png', confidence=0.8, region=info_escudo)
    
    repair = pyautogui.locateOnScreen('repair.png', confidence=0.6)
    ok = pyautogui.locateOnScreen('ok.png', confidence=0.7)

    if escudo_critico != None:
        pyautogui.click(456, 372)
        time.sleep(3)
        pyautogui.click(952, 706)
        time.sleep(3)
        pyautogui.click(repair)
        time.sleep(3)
        pyautogui.moveTo(1756, 326)
        time.sleep(3)
        pyautogui.scroll(-400)
        time.sleep(5)
        pyautogui.click(1815, 566)
        time.sleep(60)
        pyautogui.click(ok)
        time.sleep(3)
        pyautogui.click(989, 423)
        time.sleep(3)

    pyautogui.moveTo(598, 372)
    time.sleep(2)

    info_escudo = (1270, 597, 68, 50)
    escudo_critico = pyautogui.locateOnScreen('pixel_vermelho.png', confidence=0.8, region=info_escudo)
    if escudo_critico != None:
        pyautogui.click(598, 372)
        time.sleep(3)
        pyautogui.click(952, 706)
        time.sleep(3)
        pyautogui.click(repair)
        time.sleep(3)
        pyautogui.moveTo(1756, 326)
        time.sleep(3)
        pyautogui.scroll(-400)
        time.sleep(5)
        pyautogui.click(1815, 566)
        time.sleep(60)
        pyautogui.click(ok)
        time.sleep(3)
        pyautogui.click(989, 423)
        time.sleep(3)

    pyautogui.moveTo(740, 372)
    time.sleep(2)

    info_escudo = (1270, 597, 68, 50)
    escudo_critico = pyautogui.locateOnScreen('pixel_vermelho.png', confidence=0.8, region=info_escudo)
    if escudo_critico != None:

        pyautogui.click(740, 372)
        time.sleep(2)
        pyautogui.click(952, 706)
        time.sleep(3)
        pyautogui.click(repair)
        time.sleep(3)
        pyautogui.moveTo(1756, 326)
        time.sleep(3)
        pyautogui.scroll(-400)
        time.sleep(5)
        pyautogui.click(1815, 566)
        time.sleep(60)
        pyautogui.click(ok)
        time.sleep(3)
        pyautogui.click(989, 423)
        time.sleep(3)

    pyautogui.moveTo(882, 372)
    time.sleep(2)

    info_escudo = (1270, 597, 68, 50)
    escudo_critico = pyautogui.locateOnScreen('pixel_vermelho.png', confidence=0.8, region=info_escudo)
    if escudo_critico != None:

        pyautogui.click(882, 372)
        time.sleep(2)
        pyautogui.click(952, 706)
        time.sleep(3)
        pyautogui.click(repair)
        time.sleep(3)
        pyautogui.moveTo(1756, 326)
        time.sleep(3)
        pyautogui.scroll(-400)
        time.sleep(5)
        pyautogui.click(1815, 566)
        time.sleep(60)
        pyautogui.click(ok)
        time.sleep(3)
        pyautogui.click(989, 423)
        time.sleep(3)

    pyautogui.moveTo(1024, 372)
    time.sleep(2)

    info_escudo = (1270, 597, 68, 50)
    escudo_critico = pyautogui.locateOnScreen('pixel_vermelho.png', confidence=0.8, region=info_escudo)
    if escudo_critico != None:
        
        pyautogui.click(1024, 372)
        time.sleep(2)
        pyautogui.click(952, 706)
        time.sleep(3)
        pyautogui.click(repair)
        time.sleep(3)
        pyautogui.moveTo(1756, 326)
        time.sleep(3)
        pyautogui.scroll(-400)
        time.sleep(5)
        pyautogui.click(1815, 566)
        time.sleep(60)
        pyautogui.click(ok)
        time.sleep(3)
        pyautogui.click(989, 423)
        time.sleep(3)

    pyautogui.moveTo(1024, 515)
    time.sleep(2)

    info_escudo = (1270, 597, 68, 50)
    escudo_critico = pyautogui.locateOnScreen('pixel_vermelho.png', confidence=0.8, region=info_escudo)
    if escudo_critico != None:
        
        pyautogui.click(1024, 515)
        time.sleep(2)
        pyautogui.click(952, 706)
        time.sleep(3)
        pyautogui.click(repair)
        time.sleep(3)
        pyautogui.moveTo(1756, 326)
        time.sleep(3)
        pyautogui.scroll(-400)
        time.sleep(5)
        pyautogui.click(1815, 566)
        time.sleep(60)
        pyautogui.click(ok)
        time.sleep(3)
        pyautogui.click(989, 423)
        time.sleep(3)

    pyautogui.moveTo(882, 515)
    time.sleep(2)

    info_escudo = (1270, 597, 68, 50)
    escudo_critico = pyautogui.locateOnScreen('pixel_vermelho.png', confidence=0.8, region=info_escudo)
    if escudo_critico != None:
        
        pyautogui.click(882, 515)
        time.sleep(2)
        pyautogui.click(952, 706)
        time.sleep(3)
        pyautogui.click(repair)
        time.sleep(3)
        pyautogui.moveTo(1756, 326)
        time.sleep(3)
        pyautogui.scroll(-400)
        time.sleep(5)
        pyautogui.click(1815, 566)
        time.sleep(60)
        pyautogui.click(ok)
        time.sleep(3)
        pyautogui.click(989, 423)
        time.sleep(3)

    pyautogui.moveTo(740, 515)
    time.sleep(2)

    info_escudo = (1270, 597, 68, 50)
    escudo_critico = pyautogui.locateOnScreen('pixel_vermelho.png', confidence=0.8, region=info_escudo)
    if escudo_critico != None:
        
        pyautogui.click(740, 515)
        time.sleep(2)
        pyautogui.click(952, 706)
        time.sleep(3)
        pyautogui.click(repair)
        time.sleep(3)
        pyautogui.moveTo(1756, 326)
        time.sleep(3)
        pyautogui.scroll(-400)
        time.sleep(5)
        pyautogui.click(1815, 566)
        time.sleep(60)
        pyautogui.click(ok)
        time.sleep(3)
        pyautogui.click(989, 423)
        time.sleep(3)

    pyautogui.moveTo(598, 515)
    time.sleep(2)

    info_escudo = (1270, 597, 68, 50)
    escudo_critico = pyautogui.locateOnScreen('pixel_vermelho.png', confidence=0.8, region=info_escudo)
    if escudo_critico != None:
        
        pyautogui.click(598, 515)
        time.sleep(2)
        pyautogui.click(952, 706)
        time.sleep(3)
        pyautogui.click(repair)
        time.sleep(3)
        pyautogui.moveTo(1756, 326)
        time.sleep(3)
        pyautogui.scroll(-400)
        time.sleep(5)
        pyautogui.click(1815, 566)
        time.sleep(60)
        pyautogui.click(ok)
        time.sleep(3)
        pyautogui.click(989, 423)
        time.sleep(3)

    pyautogui.moveTo(456, 515)
    time.sleep(2)

    info_escudo = (1270, 597, 68, 50)
    escudo_critico = pyautogui.locateOnScreen('pixel_vermelho.png', confidence=0.8, region=info_escudo)
    if escudo_critico != None:
        
        pyautogui.click(456, 515)
        time.sleep(2)
        pyautogui.click(952, 706)
        time.sleep(3)
        pyautogui.click(repair)
        time.sleep(3)
        pyautogui.moveTo(1756, 326)
        time.sleep(3)
        pyautogui.scroll(-400)
        time.sleep(5)
        pyautogui.click(1815, 566)
        time.sleep(60)
        pyautogui.click(ok)
        time.sleep(3)
        pyautogui.click(989, 423)
        time.sleep(3)

    pyautogui.moveTo(456, 667)
    time.sleep(2)

    info_escudo = (1270, 597, 68, 50)
    escudo_critico = pyautogui.locateOnScreen('pixel_vermelho.png', confidence=0.8, region=info_escudo)
    if escudo_critico != None:
        
        pyautogui.click(456, 667)
        time.sleep(2)
        pyautogui.click(952, 706)
        time.sleep(3)
        pyautogui.click(repair)
        time.sleep(3)
        pyautogui.moveTo(1756, 326)
        time.sleep(3)
        pyautogui.scroll(-400)
        time.sleep(5)
        pyautogui.click(1815, 566)
        time.sleep(60)
        pyautogui.click(ok)
        time.sleep(3)
        pyautogui.click(989, 423)
        time.sleep(3)

    pyautogui.moveTo(598, 667)
    time.sleep(2)

    info_escudo = (1270, 597, 68, 50)
    escudo_critico = pyautogui.locateOnScreen('pixel_vermelho.png', confidence=0.8, region=info_escudo)
    if escudo_critico != None:
        
        pyautogui.click(598, 667)
        time.sleep(2)
        pyautogui.click(952, 706)
        time.sleep(3)
        pyautogui.click(repair)
        time.sleep(3)
        pyautogui.moveTo(1756, 326)
        time.sleep(3)
        pyautogui.scroll(-400)
        time.sleep(5)
        pyautogui.click(1815, 566)
        time.sleep(60)
        pyautogui.click(ok)
        time.sleep(3)
        pyautogui.click(989, 423)
        time.sleep(3)

    pyautogui.moveTo(740, 667)
    time.sleep(2)

    info_escudo = (1270, 597, 68, 50)
    escudo_critico = pyautogui.locateOnScreen('pixel_vermelho.png', confidence=0.8, region=info_escudo)
    if escudo_critico != None:
        
        pyautogui.click(740, 667)
        time.sleep(2)
        pyautogui.click(952, 706)
        time.sleep(3)
        pyautogui.click(repair)
        time.sleep(3)
        pyautogui.moveTo(1756, 326)
        time.sleep(3)
        pyautogui.scroll(-400)
        time.sleep(5)
        pyautogui.click(1815, 566)
        time.sleep(60)
        pyautogui.click(ok)
        time.sleep(3)
        pyautogui.click(989, 423)
        time.sleep(3)

    pyautogui.moveTo(882, 667)
    time.sleep(2)

    info_escudo = (1270, 597, 68, 50)
    escudo_critico = pyautogui.locateOnScreen('pixel_vermelho.png', confidence=0.8, region=info_escudo)
    if escudo_critico != None:
        
        pyautogui.click(882, 667)
        time.sleep(2)
        pyautogui.click(952, 706)
        time.sleep(3)
        pyautogui.click(repair)
        time.sleep(3)
        pyautogui.moveTo(1756, 326)
        time.sleep(3)
        pyautogui.scroll(-400)
        time.sleep(5)
        pyautogui.click(1815, 566)
        time.sleep(60)
        pyautogui.click(ok)
        time.sleep(3)
        pyautogui.click(989, 423)
        time.sleep(3)

    pyautogui.moveTo(1024, 667)
    time.sleep(2)

    info_escudo = (1270, 597, 68, 50)
    escudo_critico = pyautogui.locateOnScreen('pixel_vermelho.png', confidence=0.8, region=info_escudo)
    if escudo_critico != None:
        
        pyautogui.click(1024, 667)
        pyautogui.click(952, 706)
        time.sleep(3)
        pyautogui.click(repair)
        time.sleep(3)
        pyautogui.moveTo(1756, 326)
        time.sleep(3)
        pyautogui.scroll(-400)
        time.sleep(5)
        pyautogui.click(1815, 566)
        time.sleep(60)
        pyautogui.click(ok)
        time.sleep(3)
        pyautogui.click(989, 423)
        time.sleep(3)

